version: "3.9"

services:
  web:
    build: .
    container_name: numlk-django
    command: sh -c "uv run python manage.py migrate && uv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      PG_DB_NAME: numlock
      PG_USER: devuser
      PG_PASSWORD: devpass
      PG_HOST: localhost
      PG_PORT: 5432
    network_mode: "container:pg-dev"
