# Generated by Django 5.2.2 on 2025-08-07 19:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_remove_company_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(choices=[('AWS', 'Amazon Web Services'), ('GCP', 'Google Cloud Platform'), ('AZURE', 'Microsoft Azure')], max_length=10)),
                ('account_name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_accounts', to='organizations.company')),
            ],
            options={
                'ordering': ['vendor', 'account_name'],
                'unique_together': {('vendor', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_token', to='data.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('service_name', models.CharField(max_length=255)),
                ('resource', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='data.cloudaccount')),
            ],
            options={
                'ordering': ['-usage_start'],
                'indexes': [models.Index(fields=['usage_start', 'usage_end'], name='data_billin_usage_s_7a1856_idx')],
            },
        ),
    ]
