# Generated by Django 5.2.2 on 2025-08-15 23:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor', models.CharField(choices=[('AWS', 'Amazon Web Services'), ('GCP', 'Google Cloud Platform'), ('AZURE', 'Microsoft Azure')], max_length=10)),
                ('account_name', models.CharField(max_length=255)),
                ('account_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cloud_accounts', to='company.company')),
            ],
            options={
                'ordering': ['vendor', 'account_name'],
            },
        ),
        migrations.CreateModel(
            name='BillingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('service_category', models.CharField(max_length=255)),
                ('total_cost', models.DecimalField(decimal_places=4, max_digits=20)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AzureOAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(max_length=50)),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('tenant_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='azure_oauth_token', to='data.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='AWSRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=70)),
                ('role_arn', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aws_role_values', to='data.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='GoogleOAuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_oauth_token', to='data.cloudaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usage_start', models.DateTimeField()),
                ('usage_end', models.DateTimeField()),
                ('service_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_type', models.CharField(blank=True, max_length=50, null=True)),
                ('usage_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('usage_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('resource', models.CharField(blank=True, max_length=255, null=True)),
                ('cost', models.DecimalField(decimal_places=4, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to='data.cloudaccount')),
            ],
            options={
                'ordering': ['-usage_start'],
                'indexes': [models.Index(fields=['usage_start', 'usage_end'], name='data_billin_usage_s_7a1856_idx')],
                'unique_together': {('cloud_account', 'usage_start', 'usage_end', 'service_name', 'cost_type', 'resource')},
            },
        ),
    ]
