# Generated by Django 5.2.2 on 2025-08-17 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cloudaccount',
            unique_together={('company', 'account_name', 'account_id')},
        ),
        migrations.CreateModel(
            name='BillingAccountSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_summary', to='data.cloudaccount')),
            ],
            options={
                'unique_together': {('cloud_account', 'usage_date')},
            },
        ),
        migrations.CreateModel(
            name='BillingServiceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=255)),
                ('usage_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('total_usage', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('cloud_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_summary', to='data.cloudaccount')),
            ],
            options={
                'unique_together': {('cloud_account', 'service_name', 'usage_date')},
            },
        ),
        migrations.DeleteModel(
            name='BillingSummary',
        ),
    ]
