# Generated by Django 5.2.2 on 2025-08-08 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureOAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_type', models.CharField(max_length=50)),
                ('scope', models.TextField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('tenant_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='azure_oauth_token', to='data.cloudaccount')),
            ],
        ),
    ]
