# Generated by Django 5.2.2 on 2025-08-08 20:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_azureoauthtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(max_length=70)),
                ('role_arn', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cloud_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aws_role_values', to='data.cloudaccount')),
            ],
        ),
    ]
