# Generated by Django 5.2.2 on 2025-08-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_cloudaccount_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='billingservicesummary',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='billingservicesummary',
            name='cloud_account',
        ),
        migrations.DeleteModel(
            name='BillingAccountSummary',
        ),
        migrations.DeleteModel(
            name='BillingServiceSummary',
        ),
    ]
