# Generated by Django 5.2.2 on 2025-08-08 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_awsrole'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cloudaccount',
            unique_together=set(),
        ),
    ]
