# Generated by Django 5.2.2 on 2025-09-04 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_owner_alter_company_table_and_more"),
        ("data", "0003_alter_billingservicesummary_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cloudaccount",
            unique_together=set(),  # remove old unique_together
        ),
        migrations.AddField(
            model_name="cloudaccount",
            name="organization",
            field=models.ForeignKey(
                default="055b6503-585c-470b-b4e3-3cf9a9e382a7",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cloud_accounts",
                to="company.organization",
            ),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name="cloudaccount",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="cloudaccount",
            unique_together={("organization", "account_name", "account_id")},
        ),
    ]
