# Generated by Django 5.1.7 on 2025-04-19 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_navigation"),
    ]

    operations = [
        migrations.AddField(
            model_name="navigation",
            name="icon",
            field=models.CharField(default="Hand", max_length=20),
            preserve_default=False,
        ),
    ]
