# Generated by Django 5.1.7 on 2025-04-29 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_auto_20250429_2346"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="organizations.company"
            ),
        ),
    ]
