# Generated by Django 5.1.7 on 2025-05-15 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_alter_organization_company"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="invitation",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="navigation",
            options={"ordering": ["label"]},
        ),
        migrations.AlterModelOptions(
            name="organization",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="organizationmembership",
            options={"ordering": ["joined_at"]},
        ),
        migrations.AddField(
            model_name="navigation",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this navigation is a sub-navigation of the selected navigation.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_navigations",
                to="organizations.navigation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invitation",
            unique_together={("organization", "invitee_email")},
        ),
    ]
