# Generated by Django 5.1.7 on 2025-05-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0009_alter_company_options_alter_invitation_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="navigation",
            name="icon",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
