# Generated by Django 5.1.7 on 2025-05-20 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0010_alter_navigation_icon"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyColorScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "sidebar_accent",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("borders", models.CharField(blank=True, max_length=7, null=True)),
                (
                    "form_input_background",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "sidebar_background",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "sidebar_font_color",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="color_scheme",
                        to="organizations.company",
                    ),
                ),
            ],
        ),
    ]
