# Generated by Django 5.1.7 on 2025-05-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0011_companycolorscheme"),
    ]

    operations = [
        migrations.AddField(
            model_name="companycolorscheme",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
