# Generated by Django 5.1.7 on 2025-05-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0012_companycolorscheme_logo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companycolorscheme",
            name="logo",
        ),
        migrations.AddField(
            model_name="company",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="company_logos/"),
        ),
    ]
