# Generated by Django 5.1.7 on 2025-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0013_remove_companycolorscheme_logo_company_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="navigation",
            options={"ordering": ["parent_id", "order", "label"]},
        ),
        migrations.AddField(
            model_name="navigation",
            name="order",
            field=models.PositiveIntegerField(default=0, help_text="Custom order"),
        ),
    ]
