# Generated by Django 5.2.2 on 2025-06-09 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='organization',
            field=models.ForeignKey(default='57923ab1-87f3-4780-a8b0-50a0310e7ee4', on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
            preserve_default=False,
        ),
    ]
