# Generated by Django 5.2.2 on 2025-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0016_usergroup_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='invitations', to='organizations.usergroup'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='user_groups',
            field=models.ManyToManyField(blank=True, related_name='navigations', to='organizations.usergroup'),
        ),
    ]
