# Generated by Django 5.1.7 on 2025-04-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companymember",
            name="company",
        ),
        migrations.AlterUniqueTogether(
            name="companymember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="companymember",
            name="user",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="CompanyMember",
        ),
    ]
