# Generated by Django 5.2.2 on 2025-09-09 13:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_squashed_0002_remove_companymember_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimeCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('secret', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('magic_link', 'Magic Link'), ('otp', 'One-Time Password')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'type', 'expires_at'], name='authenticat_user_id_e6b6ca_idx')],
            },
        ),
    ]
