# Generated by Django 5.1.7 on 2025-03-25 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0006_user_is_email_verified"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
