# Generated by Django 5.2.2 on 2025-09-06 09:08

import django.db.models.deletion
from django.db import migrations, models


def create_themes(apps, schema_editor):
    Theme = apps.get_model("company", "Theme")
    themes = [
        ("default", "Default"),
        ("simple", "Simple"),
        ("classic", "Classic"),
        ("amber-minimal", "Amber Minimal"),
        ("bold-tech", "Bold Tech"),
        ("caffeine", "Caffeine"),
        ("elegant-luxury", "Elegant Luxury"),
    ]
    for value, label in themes:
        Theme.objects.get_or_create(value=value, defaults={"label": label})


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0002_company_owner_alter_company_table_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Theme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Theme",
                "verbose_name_plural": "Themes",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="theme",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="companies",
                to="company.theme",
            ),
        ),
        migrations.RunPython(create_themes),
    ]
