# Generated by Django 5.2.2 on 2025-09-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_theme_company_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='theme',
            field=models.CharField(choices=[('default', 'Default'), ('simple', 'Simple'), ('classic', 'Classic'), ('amber-minimal', 'Amber Minimal'), ('bold-tech', 'Bold Tech'), ('caffeine', 'Caffeine'), ('elegant-luxury', 'Elegant Luxury')], default='default', max_length=50),
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
